spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
endpoints:
  health:
    sensitive: false
#logging:
#  file: /tmp/@artifactId@.json
---
server:
  port: @server.port@
---
# bm poller
bm:
  pooling:
    url: @bm.polling.url@
    maxPoolSize: @bm.polling.maxPoolSize@
    delay: @bm.polling.delay@

file:
  pathToFolder: @file.pathToFolder@

mail:
  host: secure.emailsrvr.com
  port: 587
  username: no-reply@rbkmoney.com
  password: EIPe6wGYOC9StdFP
  from: no-reply@rbkmoney.com
  protocol: smtp
  smtps:
    auth: true
    starttls:
      enable: true

test:
  mail:
    to: @test.mail.to@
  server:
    port:7778

notification:
  payment:
    paid:
      from: no-reply@rbkmoney.com
      fileNameTemplate: payment_paid.ftl
  create:
    invoice:
      from: no-reply@rbkmoney.com
      fileNameTemplate: create_invoice.ftl

spring:
  freemarker:
    template-loader-path: classpath:templates/
    prefer-file-system-access: true
    charset: UTF-8
