info:
  version: @version@
  stage: dev
  scheduler-pool-size: 4
  damsel:
    version: @damsel.version@

server:
  port: @server.port@

spring:
  application:
    name: @name@
    description: @description@
  freemarker:
    template-loader-path: classpath:templates/
    prefer-file-system-access: true
    charset: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000

retry-policy:
  maxAttempts: -1

management:
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false

db:
  jdbc:
    tr_timeout: 300000

invoicing-service:
  url: http://invoicing:8023/v1/invoicing
  networkTimeout: 120000

message:
  fail:
    minutes: 5
  store:
    days: 3
  schedule:
    clear:
      sent: 86400000 # every day
      failed: 300000 # every 5 minutes
    send: 500 # 500 ms after completion of prev. execution
  sending.concurrency: 8

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: dudoser
  ssl:
    enabled: false
#    trust-store-location: "test"
#    trust-store-password: "test"
#    key-store-location: "test"
#    key-store-password: "test"
#    key-password: "test"
#    key-store-type: PKCS12
#    trust-store-type: PKCS12
  consumer:
    concurrency: 8
    group-id: "DudoserListener"
    enable-auto-commit: false
    auto-offset-reset: latest
    max-poll-records: 20
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false

---

hellgate:
  url: http://hellgate:8022/v1/processing/partymgmt
  networkTimeout: 30000

mail:
  host: rbkmoney.com
  port: 587
  username: no-reply@rbkmoney.com
  password: jah;qu5chaeJeoCo
  from: no-reply@rbkmoney.com
  protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
    timeout: 30000

test:
  mail:
    to: i.arsanukaev@rbkmoney.com
  server:
    port: 7778

notification:
  payment:
    paid:
      from: no-reply@rbkmoney.com
      fileNameTemplate: payment_paid.ftl
  create:
    invoice:
      from: no-reply@rbkmoney.com
      fileNameTemplate: create_invoice.ftl
