spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
  damsel:
    version: @damsel.version@
---
#logging:
#  file: /tmp/@artifactId@.json
---
server:
  port: @server.port@
---
# bm poller
bm:
  pooling:
    url: http://localhost:8023/repo
    maxPoolSize: 1
    delay: 5000

hellgate:
  url: http://hellgate:8022/v1/processing/partymgmt
  networkTimeout: 30000

mail:
  host: smtp.office365.com
  port: 587
  username: no-reply@rbkmoney.com
  password: jah;qu5chaeJeoCo
  from: no-reply@rbkmoney.com
  protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
    timeout: 30000

test:
  mail:
    to: i.arsanukaev@rbkmoney.com
  server:
    port:7778

notification:
  payment:
    paid:
      from: no-reply@rbkmoney.com
      fileNameTemplate: payment_paid.ftl
  create:
    invoice:
      from: no-reply@rbkmoney.com
      fileNameTemplate: create_invoice.ftl

spring:
  freemarker:
    template-loader-path: classpath:templates/
    prefer-file-system-access: true
    charset: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
management:
  security:
    enabled: false
