spring:
  application:
    name: @name@
    description: @description@

retry-policy:
  maxAttempts: -1

message:
  store:
    days: 3
  schedule:
    clear: 86400 # every day
    send: 15000 # 15 seconds


kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: dudoser
  ssl:
    enabled: false
#    trust-store-location: "test"
#    trust-store-password: "test"
#    key-store-location: "test"
#    key-store-password: "test"
#    key-password: "test"
#    key-store-type: PKCS12
#    trust-store-type: PKCS12
  consumer:
    concurrency: 8
    group-id: "DudoserListener"
    enable-auto-commit: false
    auto-offset-reset: latests
    max-poll-records: 200
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false

---
info:
  version: @version@
  stage: dev
  damsel:
    version: @damsel.version@
---
server:
  port: @server.port@
---

hellgate:
  url: http://hellgate:8022/v1/processing/partymgmt
  networkTimeout: 30000

mail:
  host: rbkmoney.com
  port: 587
  username: no-reply@rbkmoney.com
  password: jah;qu5chaeJeoCo
  from: no-reply@rbkmoney.com
  protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true
    timeout: 30000

test:
  mail:
    to: i.arsanukaev@rbkmoney.com
  server:
    port: 7778

notification:
  payment:
    paid:
      from: no-reply@rbkmoney.com
      fileNameTemplate: payment_paid.ftl
  create:
    invoice:
      from: no-reply@rbkmoney.com
      fileNameTemplate: create_invoice.ftl

spring:
  freemarker:
    template-loader-path: classpath:templates/
    prefer-file-system-access: true
    charset: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
