spring:
  application:
    name: @name@
    description: @description@
---
info:
  version: @version@
  responsible: Anatoly Cherkasov
  stage: dev
---
endpoints:
  health:
    sensitive: false
#logging:
#  file: /tmp/@artifactId@.json
---
server:
  port: @server.port@
---
# bm poller
bm:
  pooling:
    url: http://localhost:8023/repo
    maxPoolSize: 1
    delay: 5000

mail:
  host: smtp.office365.com
  port: 587
  username: no-reply@rbkmoney.com
  password: be:thoim3Ae1xeiC
  from: no-reply@rbkmoney.com
  protocol: smtp
  smtp:
    auth: true
    starttls:
      enable: true

test:
  mail:
    to: i.arsanukaev@rbkmoney.com
  server:
    port:7778

notification:
  payment:
    paid:
      from: no-reply@rbkmoney.com
      fileNameTemplate: payment_paid.ftl
  create:
    invoice:
      from: no-reply@rbkmoney.com
      fileNameTemplate: create_invoice.ftl

spring:
  freemarker:
    template-loader-path: classpath:templates/
    prefer-file-system-access: true
    charset: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      maximum-pool-size: 3
      idle-timeout: 30000
