/**
 * This class is generated by jOOQ
 */
package com.rbkmoney.dudoser.domain;


import com.rbkmoney.dudoser.domain.tables.LastEventId;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Dudos extends SchemaImpl {

    private static final long serialVersionUID = -722655663;

    /**
     * The reference instance of <code>dudos</code>
     */
    public static final Dudos DUDOS = new Dudos();

    /**
     * The table <code>dudos.last_event_id</code>.
     */
    public final LastEventId LAST_EVENT_ID = com.rbkmoney.dudoser.domain.tables.LastEventId.LAST_EVENT_ID;

    /**
     * No further instances allowed
     */
    private Dudos() {
        super("dudos", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                LastEventId.LAST_EVENT_ID);
    }
}
