/**
 * This class is generated by jOOQ
 */
package com.rbkmoney.dudoser.domain;


import com.rbkmoney.dudoser.domain.tables.Javaobject;
import com.rbkmoney.dudoser.domain.tables.LastEventId;
import com.rbkmoney.dudoser.domain.tables.records.JavaobjectRecord;
import com.rbkmoney.dudoser.domain.tables.records.LastEventIdRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>dudos</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JavaobjectRecord, Long> IDENTITY_JAVAOBJECT = Identities0.IDENTITY_JAVAOBJECT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JavaobjectRecord> JAVAOBJECT_PKEY = UniqueKeys0.JAVAOBJECT_PKEY;
    public static final UniqueKey<LastEventIdRecord> EVENT_PKEY = UniqueKeys0.EVENT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<JavaobjectRecord, Long> IDENTITY_JAVAOBJECT = createIdentity(Javaobject.JAVAOBJECT, Javaobject.JAVAOBJECT.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<JavaobjectRecord> JAVAOBJECT_PKEY = createUniqueKey(Javaobject.JAVAOBJECT, "javaobject_pkey", Javaobject.JAVAOBJECT.ID);
        public static final UniqueKey<LastEventIdRecord> EVENT_PKEY = createUniqueKey(LastEventId.LAST_EVENT_ID, "event_pkey", LastEventId.LAST_EVENT_ID.ID);
    }
}
