/**
 * This class is generated by jOOQ
 */
package com.rbkmoney.dudoser.domain;


import com.rbkmoney.dudoser.domain.tables.LastEventId;
import com.rbkmoney.dudoser.domain.tables.records.LastEventIdRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>dudos</code>
 * schema
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LastEventIdRecord> EVENT_PKEY = UniqueKeys0.EVENT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<LastEventIdRecord> EVENT_PKEY = createUniqueKey(LastEventId.LAST_EVENT_ID, "event_pkey", LastEventId.LAST_EVENT_ID.ID);
    }
}
