/**
 * This class is generated by jOOQ
 */
package com.rbkmoney.dudoser.domain;


import com.rbkmoney.dudoser.domain.tables.LastEventId;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in dudos
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>dudos.last_event_id</code>.
     */
    public static final LastEventId LAST_EVENT_ID = com.rbkmoney.dudoser.domain.tables.LastEventId.LAST_EVENT_ID;
}
