/**
 * This class is generated by jOOQ
 */
package com.rbkmoney.dudoser.domain.tables;


import com.rbkmoney.dudoser.domain.Dudos;
import com.rbkmoney.dudoser.domain.Keys;
import com.rbkmoney.dudoser.domain.tables.records.LastEventIdRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LastEventId extends TableImpl<LastEventIdRecord> {

    private static final long serialVersionUID = 1298799363;

    /**
     * The reference instance of <code>dudos.last_event_id</code>
     */
    public static final LastEventId LAST_EVENT_ID = new LastEventId();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LastEventIdRecord> getRecordType() {
        return LastEventIdRecord.class;
    }

    /**
     * The column <code>dudos.last_event_id.id</code>.
     */
    public final TableField<LastEventIdRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dudos.last_event_id.event_id</code>.
     */
    public final TableField<LastEventIdRecord, Long> EVENT_ID = createField("event_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>dudos.last_event_id</code> table reference
     */
    public LastEventId() {
        this("last_event_id", null);
    }

    /**
     * Create an aliased <code>dudos.last_event_id</code> table reference
     */
    public LastEventId(String alias) {
        this(alias, LAST_EVENT_ID);
    }

    private LastEventId(String alias, Table<LastEventIdRecord> aliased) {
        this(alias, aliased, null);
    }

    private LastEventId(String alias, Table<LastEventIdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dudos.DUDOS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LastEventIdRecord> getPrimaryKey() {
        return Keys.EVENT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LastEventIdRecord>> getKeys() {
        return Arrays.<UniqueKey<LastEventIdRecord>>asList(Keys.EVENT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LastEventId as(String alias) {
        return new LastEventId(alias, this);
    }

    /**
     * Rename this table
     */
    public LastEventId rename(String name) {
        return new LastEventId(name, null);
    }
}
